---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "clickhouse.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.configEnvs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-config-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "clickhouse.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.secretConfigEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
