collector:
  mode: ""
  replicas: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  logsReceivers: []
  metricsReceivers: []
  tracesReceivers: []
  envs:
    CLICKHOUSE_ENDPOINT: tcp://127.0.0.1:9000
    CLICKHOUSE_USER: clickhouse
    CLICKHOUSE_DB: clickhouse
  secretEnvs:
    CLICKHOUSE_PASSWORD: Secret123
  mountLogs: false

targetAllocator:
  enabled: false
  replicas: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 1000m
      memory: 1Gi
