collector:
  mode: ""
  replicas: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 1000m
      memory: 1Gi

  logsReceivers: []
  metricsReceivers: []
  tracesReceivers: []
  envs:
    CLICKHOUSE_ENDPOINT: ""
    CLICKHOUSE_USERNAME: ""
  secretEnvs:
    CLICKHOUSE_PASSWORD: ""
  mountLogs: false

targetAllocator:
  enabled: false
  replicas: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 1000m
      memory: 1Gi
