manager:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
kubeRBACProxy:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
testFramework:
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits: {}
