apiVersion: v2
name: undefined
version: 0.0.0
dependencies:
  - # https://github.com/cert-manager/cert-manager/tree/master/deploy/charts/cert-manager
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v1.19.1
  - # https://github.com/cilium/cilium/tree/main/install/kubernetes/cilium
    repository: https://helm.cilium.io
    name: cilium
    version: 1.18.4
  - # https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-operator
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    name: opentelemetry-operator
    version: 0.99.2
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-operator-crds
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-operator-crds
    version: 25.0.0
  - # https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero
    repository: https://vmware-tanzu.github.io/helm-charts
    name: velero
    version: 11.2.0
