apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "grafana.metadataLabels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" $ | nindent 6 }}
  replicas: {{ .Values.minReplicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.maxUnavailable }}
  template:
    metadata:
      labels:
        {{- include "grafana.metadataLabels" $ | nindent 8 }}
        {{- if .Values.extraPodLabels }}
        {{- toYaml .Values.extraPodLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/configs: "{{ include "grafana.configsChecksum" $ }}"
        {{- if .Values.extraPodAnnotations }}
        {{- toYaml .Values.extraPodAnnotations | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: "{{ .Values.serviceAccountName }}"
      {{- else }}
      serviceAccountName: "{{ .Release.Name }}"
      {{- end }}
      containers:
        - name: grafana-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
            - configMapRef:
                name: "{{ .Release.Name }}-config-envs"
            - secretRef:
                name: "{{ .Release.Name }}-config-envs"
          volumeMounts:
            - name: config-files
              mountPath: /etc/grafana
              readOnly: true
          ports:
            - name: grafana-http
              containerPort: 3000
              protocol: TCP
          startupProbe:
            httpGet:
              port: grafana-http
              path: /api/health
          readinessProbe:
            httpGet:
              port: grafana-http
              path: /api/health
          livenessProbe:
            httpGet:
              port: grafana-http
              path: /api/health
          resources:
            requests:
              cpu: 1m
              memory: 1Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext: # container security context
            privileged: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            runAsUser: 472
            runAsGroup: 472
      securityContext: # pod security context
        fsGroup: 472
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "grafana.selectorLabels" $ | nindent 20 }}
                topologyKey: kubernetes.io/hostname
      volumes:
        - name: config-files
          projected:
            sources:
              - configMap:
                  name: "{{ .Release.Name }}-config-files"
              - secret:
                  name: "{{ .Release.Name }}-config-files"
