apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "grafana.metadataLabels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" $ | nindent 6 }}
  maxUnavailable: {{ .Values.maxUnavailable }}
