{{- if not .Values.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "grafana.metadataLabels" $ | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
