apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "grafana.metadataLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - "{{ .Release.Namespace }}"
  endpoints:
    - port: grafana-http
      path: /metrics
      interval: 30s
