apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "grafana.metadataLabels" . | nindent 4 }}
    {{- if .Values.extraServiceLabels }}
    {{- toYaml .Values.extraServiceLabels | nindent 4 }}
    {{- end }}
  annotations:
    networking.gke.io/max-rate-per-endpoint: "100"
    {{- if .Values.extraServiceAnnotations }}
    {{- toYaml .Values.extraServiceAnnotations | nindent 4 }}
    {{- end }}
spec:
  selector:
    {{- include "grafana.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  ports:
    - name: grafana-http
      port: 80
      protocol: TCP
      targetPort: grafana-http
