# https://hub.docker.com/_/postgres
image:
  repository: postgres
  tag: 18.1

envs:
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
secretEnvs:
  POSTGRES_PASSWORD: Secret123

resources:
  requests:
    cpu: 1m
    memory: 1Mi
    storage: 10Gi
  limits:
    cpu: 1000m
    memory: 1Gi

extraPodLabels: {}
extraPodAnnotations: {}
