---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "configs.metadataLabels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-config-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "configs.metadataLabels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secretEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config-files"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "configs.metadataLabels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.files }}
  {{ include "configs.key" $key }}: |
    {{- if hasSuffix ".yaml" $key }}
    {{- toYaml $val | nindent 4 }}
    {{- else }}
    {{- $val | nindent 4 }}
    {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-config-files"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "configs.metadataLabels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.secretFiles }}
  {{- if hasSuffix ".yaml" $key }}
  {{ include "configs.key" $key }}: {{ toYaml $val | b64enc | quote }}
  {{- else }}
  {{ include "configs.key" $key }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
