# https://hub.docker.com/_/postgres
image:
  repository: postgres
  tag: 18.1

envs: {}
secretEnvs: {}

resources:
  requests:
    cpu: 1m
    memory: 1Mi
    storage: 10Gi
  limits:
    cpu: 1000m
    memory: 1Gi

extraPodLabels: {}
extraPodAnnotations: {}
