service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlphttp/elasticsearch]

  extensions:
    - health_check
