service:
  pipelines:
    metrics:
      receivers: [kubeletstats]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlp/clickstack]

  extensions:
    - health_check
