service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlphttp/elasticsearch]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlphttp/elasticsearch]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlphttp/elasticsearch]

  extensions:
    - health_check
