service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlp/clickstack]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlp/clickstack]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [otlp/clickstack]

  extensions:
    - health_check
