service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, filter, k8sattributes, batch]
      exporters: [prometheusremotewrite/metricbeat]

  extensions:
    - health_check
