---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "postgres.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.envs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "postgres.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.secretEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
