# https://hub.docker.com/r/grafana/grafana
image:
  repository: grafana/grafana
  tag: 12.3.0

serviceAccountName: ""

configEnvs: {}
secretConfigEnvs: {}
configFiles: {}
secretConfigFiles: {}

minReplicas: 1
maxReplicas: 1
maxUnavailable: 1
extraPodLabels: {}
extraPodAnnotations: {}
