# https://hub.docker.com/r/grafana/grafana
image:
  repository: grafana/grafana
  tag: 12.3.0

configEnvs: {}
secretConfigEnvs: {}
configFiles: {}
secretConfigFiles: {}

httpServer:
  minReplicas: 1
  maxReplicas: 1
  maxUnavailable: 1
  extraPodLabels: {}
  extraPodAnnotations: {}
