# https://hub.docker.com/r/grafana/grafana
image:
  repository: grafana/grafana
  tag: 12.3.0

serviceAccountName: ""

configEnvs: {}
secretConfigEnvs: {}
configFiles: {}
secretConfigFiles: {}

minReplicas: 1
maxReplicas: 1
maxUnavailable: 1
resources:
  requests:
    cpu: 1m
    memory: 1Mi
  limits:
    cpu: 1000m
    memory: 1Gi

extraPodLabels: {}
extraPodAnnotations: {}
