# https://hub.docker.com/_/clickhouse
image:
  repository: clickhouse
  tag: 25.11

configEnvs:
  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_DB: clickhouse
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
secretConfigEnvs:
  CLICKHOUSE_PASSWORD: Secret123
configFiles: {}
secretConfigFiles: {}

extraPodLabels: {}
extraPodAnnotations: {}
extraServiceLabels: {}
extraServiceAnnotations: {}
resources:
  requests:
    cpu: 1m
    memory: 1Mi
    storage: 10Gi
  limits:
    cpu: 1000m
    memory: 1Gi
