# https://hub.docker.com/_/clickhouse
image:
  repository: clickhouse
  tag: 25.11

envs: {}
secretEnvs: {}

resources:
  requests:
    cpu: 1m
    memory: 1Mi
    storage: 10Gi
  limits:
    cpu: 1000m
    memory: 1Gi

extraPodLabels: {}
extraPodAnnotations: {}
