# https://hub.docker.com/_/clickhouse
image:
  repository: clickhouse
  tag: 25.11

envs:
  CLICKHOUSE_USER: clickhouse
  CLICKHOUSE_DB: clickhouse
  CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"
secretEnvs:
  CLICKHOUSE_PASSWORD: Secret123

resources:
  requests:
    cpu: 1m
    memory: 1Mi
    storage: 10Gi
  limits:
    cpu: 1000m
    memory: 1Gi

extraPodLabels: {}
extraPodAnnotations: {}
