---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.configEnvs }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-config-envs"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.secretConfigEnvs }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config-files"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.configFiles }}
  {{ $key | replace "/" "..." }}: |
    {{- if hasSuffix ".yaml" $key }}
    {{- toYaml $val | nindent 4 }}
    {{- else }}
    {{- $val | nindent 4 }}
    {{- end }}
  {{- end }}

---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-config-files"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "kuard.metadataLabels" $ | nindent 4 }}
data:
  {{- range $key, $val := .Values.secretConfigFiles }}
  {{- if hasSuffix ".yaml" $key }}
  {{ $key | replace "/" "..." }}: {{ toYaml $val | b64enc | quote }}
  {{- else }}
  {{ $key | replace "/" "..." }}: {{ $val | b64enc | quote }}
  {{- end }}
  {{- end }}
