apiVersion: v2
name: undefined
version: 0.0.0
dependencies:
  - # https://github.com/grafana/helm-charts/tree/main/charts/grafana
    repository: https://grafana.github.io/helm-charts
    name: grafana
    version: 10.3.0
  - # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus-blackbox-exporter
    version: 11.5.0
