image:
  repository: europe-central2-docker.pkg.dev/gogcp-main-7/private-docker-images/gorun/demo/kuard
  tag: 0.7.100

configEnvs: {}
secretConfigEnvs: {}
configFiles: {}
secretConfigFiles: {}

httpServer:
  serviceAccountName: ""
  extraPodLabels: {}
  extraPodAnnotations: {}
  extraServiceLabels: {}
  extraServiceAnnotations: {}
  minReplicas: 1
  maxReplicas: 1
  maxUnavailable: 1
  resources:
    requests:
      cpu: 1m
      memory: 1Mi
    limits:
      cpu: 1000m
      memory: 1Gi
