name: apps-tfmod-test
on:
  pull_request:
    paths:
      - "projects/apps/terraform-modules/test/**"
      - "!projects/apps/terraform-modules/test/README.md"
  push:
    branches:
      - main
    paths:
      - "projects/apps/terraform-modules/test/**"
      - "!projects/apps/terraform-modules/test/README.md"
jobs:
  apps-tfmod-test:
    name: apps-tfmod-test
    runs-on: ubuntu-24.04
    container: ghcr.io/damianagape/gorun-devcontainer:0.7.103
    permissions:
      contents: write
      id-token: write
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: git clone (not PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: git clone (fix)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: git config user
        run: git config --global user.name "github-actions" && git config --global user.email "github-actions@github.com"

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: apps-tfmod-test
          path: |
            projects/apps/terraform-modules/test/.terraform

      - name: test
        run: ./scripts/terraform-module test "projects/apps/terraform-modules/test"
      - name: init
        run: terraform -chdir="projects/apps/terraform-modules/test" init -input=false
      - name: plan
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: terraform -chdir="projects/apps/terraform-modules/test" plan -input=false
      - name: apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform -chdir="projects/apps/terraform-modules/test" apply -input=false -auto-approve
