name: decisions-0003-otel-backend-signoz
on:
  pull_request:
    paths:
      - "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz/**"
      - "!docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz/README.md"
  push:
    branches:
      - main
    paths:
      - "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz/**"
      - "!docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz/README.md"
jobs:
  decisions-0003-otel-backend-signoz:
    name: decisions-0003-otel-backend-signoz
    runs-on: ubuntu-24.04
    container: ghcr.io/damianagape/gorun-devcontainer:0.7.100
    permissions:
      contents: write
      id-token: write
    env:
      DOCKER_BUILDKIT: 1
      HELM_EXPERIMENTAL_OCI: 1
      TF_IN_AUTOMATION: 1
    steps:
      - name: git clone (PR)
        if: github.event_name == 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: git clone (not PR)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
      - name: git clone (fix)
        run: git config --system --add safe.directory "$GITHUB_WORKSPACE"
      - name: git config user
        run: git config --global user.name "github-actions" && git config --global user.email "github-actions@github.com"

      - name: gcloud auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          create_credentials_file: true
          cleanup_credentials: true
      - name: cache
        uses: actions/cache@v4
        with:
          key: decisions-0003-otel-backend-signoz
          path: |
            docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz/.terraform
            docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz/.terraform.lock.hcl

      - name: build
        run: ./scripts/terraform-submodule build "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz"
      - name: test
        run: ./scripts/terraform-submodule test "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz"
      - name: pre-publish
        if: github.event_name == 'pull_request' && github.base_ref == 'main'
        run: ./scripts/terraform-submodule pre-publish "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz"
      - name: publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./scripts/terraform-submodule publish "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz"
      - name: show
        run: ./scripts/terraform-submodule show "docs/decisions/0003-otel-backend/signoz/projects/o11y/terraform-submodules/k8s-signoz"
